--TABELA AGENDAMENTOS

create sequence tbl_agendamento_consulta_seq nocache;

--drop table ICESP.ICESP_PRJ045_TBL001;

create table tbl_agendamento_consulta
(
tp_consulta varchar2(100),
cd_unidade_executante number(11),
id_age_consulta_hor number(11),
id_age_consulta number(11),
age_consulta_nome varchar2(60),
id_especialidade number(11),
nm_especialidade varchar2(50),
cd_dia number(1),
dt_agenda varchar2(10),
hr_ini varchar2(8),
hr_fim varchar2(8),
tp_evento varchar2(1),
id_motivo number(3),
id_profissional number(11),
doc_profissional varchar2(45),
origem varchar2(45),
nm_profissional varchar2(60),
id_protocolo number(11),
subcateg varchar2(4),
nm_protocolo varchar2(100),
cd_unidade_solicitante number(11),
nm_unidade_solicitante varchar2(100),
cnes_unidade_solicitante varchar2(7),
nm_usuario_solicitante varchar2(100),
dt_ultima_atualiz varchar2(20),
cd_cliente number(11),
nm_cliente varchar2(60),
ie_sexo varchar2(1),
dt_nasc varchar2(10),
rg varchar2(20),
cpf varchar2(25),
nm_mae varchar2(60),
nm_pai varchar2(60),
ds_endereco varchar2(60),
ds_endereco_numero varchar2(5),
ds_bairro varchar2(60),
ds_municipio varchar2(60),
uf varchar2(2),
nr_cep varchar2(9),
tel_res_ddd varchar2(2),
tel_res varchar2(10),
tel_celular_ddd varchar2(2),
tel_celular varchar2(10),
tel_com_ddd varchar2(2),
tel_com varchar2(9),
tel_com_ramal varchar2(5),
ds_email varchar2(80),
contato_nome varchar2(60),
contato_tel_ddd varchar2(2),
contato_tel varchar2(10),
nr_cns number(16),
nr_prontuario number(11),
cd_raca number(1),
cd_etnia number(1),
--controle interno
nr_sequencia number(30) default tbl_agendamento_consulta_seq.nextval primary key,
dt_atualizacao date default sysdate,
nr_seq_agend_sis number(10),
cd_pessoa_sis varchar2(10)
);
